<?php
$featuredProducts = $this->getFeaturedProducts();
?>
<ul class="products-grid products-grid--max-4-col ">
<?php foreach($featuredProducts as $featuredProduct) : ?>
    <li class="item">
        <a href="<?php echo $featuredProduct->getProductUrl();?>">
            <img src="<?php echo Mage::helper('catalog/image')->init($featuredProduct, 'image')->resize(280,280)?>" alt="<?php echo $featuredProduct->getName(); ?>"/>
        </a>
        <p><?php echo $featuredProduct->getRating(); ?></p>
        <p><?php echo $featuredProduct->getName(); ?>
      
        <span><?php echo $this->getPrice($featuredProduct); ?></span></p>
    </li>
<?php endforeach; ?>
</ul>